### ISSUE TITLE
Cannot update issue resolution

### ISSUE THREAD

**Issue by vuquangtam** [ahungry/org-jira#183]
When i update an issue. It raise this error when i try to update resolution field

`cdr: Wrong type argument: listp, ("worklog" . "Log Work (required: nil)")`

Trace in source code, i found that the error raise in function: `org-jira-read-resolution` when calling `(org-jira-find-value resolution 'name)` (line 1867).

Do you have solution for this.

Thanks

**Comment by mjburling** [comment]
I'm having a similar issue with not being able to update an issue's resolution when progressing to `Closed`. My failure appears to be on `org-jira-find-value` on a custom field:

```
org-jira-find-value: Wrong type argument: listp, ("customfield_10029" . "Testers (required: nil)")
```

So far, everything else has been working extremely well, but this issue has thrown me a bit. It's not a show stopped–I can still Close/Resolve through the Web Browser, but interacting with JIRA without actually using JIRA? A man can dream...

**Comment by ahungry** [comment]
This is pretty old, I am going to assume it was resolved or was an edge case that hasn't occurred for others.

**Comment by TristanCacqueray** [comment]
Hello @ahungry , alas this is still happening on 4.4.2, using `org-jira-progress-issue` yield the following backtrace when trying to set the "resolution" on "Closed" status:

```
Debugger entered--Lisp error: (wrong-type-argument listp ("resolution" . "Resolution (required: t)"))
  org-jira-find-value(("resolution" . "Resolution (required: t)") name)
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_77>(("resolution" . "Resolution (required: t)"))
  org-jira-read-resolution()
  org-jira-progress-issue()
  funcall-interactively(org-jira-progress-issue)
  command-execute(org-jira-progress-issue record)
  #<subr execute-extended-command>(nil "org-jira-progress-issue" "org-jira-pr")
  ad-Advice-execute-extended-command(#<subr execute-extended-command> nil "org-jira-progress-issue" "org-jira-pr")
  apply(ad-Advice-execute-extended-command #<subr execute-extended-command> (nil "org-jira-progress-issue" "org-jira-pr"))
  execute-extended-command(nil "org-jira-progress-issue" "org-jira-pr")
  funcall-interactively(execute-extended-command nil "org-jira-progress-issue" "org-jira-pr")
  command-execute(execute-extended-command)
```
